version: 2

models:
  - name: stg_countries
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [country_name, country_iso2]

  - name: stg_players
    columns:
      - name: player_id
        tests: [not_null, unique]
      - name: player_name
        tests: [not_null]

  - name: dim_clubs
    columns:
      - name: club_sk
        tests: [not_null, unique]
      - name: club_name
        tests: [not_null]

  - name: dim_countries
    columns:
      - name: country_sk
        tests: [not_null, unique]
      - name: country_name
        tests: [not_null]

  - name: dim_players
    columns:
      - name: player_sk
        tests: [not_null, unique]
      - name: player_id
        tests: [not_null, unique]
      - name: nationality_country_sk
        tests:
          - relationships:
              to: ref('dim_countries')
              field: country_sk

  - name: fct_transfers
    columns:
      - name: transfer_sk
        tests: [not_null, unique]
      - name: player_sk
        tests:
          - relationships:
              to: ref('dim_players')
              field: player_sk
      - name: from_club_sk
        tests:
          - relationships:
              to: ref('dim_clubs')
              field: club_sk
      - name: to_club_sk
        tests:
          - relationships:
              to: ref('dim_clubs')
              field: club_sk
