repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.4.2
  hooks:
    - id: sqlfluff-lint
      args: ["--dialect", "duckdb", "--templater", "dbt"]
      additional_dependencies:
        - sqlfluff-templater-dbt==3.4.2
        - dbt-core==1.10.13
        - dbt-duckdb==1.9.6
      files: ^dbt/models/
      exclude: ^dbt/seeds/|^target/|^logs/
    - id: sqlfluff-fix
      args: ["--dialect", "duckdb", "--templater", "dbt"]
      additional_dependencies:
        - sqlfluff-templater-dbt==3.4.2
        - dbt-core==1.10.13
        - dbt-duckdb==1.9.6
      files: ^dbt/models/
      exclude: ^dbt/seeds/|^target/|^logs/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: ["--fix"]
      exclude: ^python_scripts/.*\.ipynb$
    - id: ruff-format
      exclude: ^python_scripts/.*\.ipynb$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
