name: dbt_pfl_statistics
version: 1.0.0
config-version: 2

profile: dbt_pfl_statistics

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  +materialized: view
  dbt_pfl_statistics:
    staging:
      +schema: staging
    marts:
      +schema: analytics


seeds:
  +quote_columns: false
  +column_types:
    club_involved_name: text
    club_involved_country: text